### PR TITLE
Add a step to install ghcup if it's not already present

### PR DESCRIPTION
**Pull request by neilmayhew**
It seems unwise to assume that `ghcup` will be in the runner environment.

In addition, when using [nektos/act](https://github.com/nektos/act) to test actions locally, `ghcup` isn't found and workflows using `setup-haskell` fail. This change fixes that. It does nothing if `ghcup` is already present, so there's no cost when running on the real GHA runner.

### CODE REVIEW

**Comment by neilmayhew** [comment]
cc @newhoggy @jasagredo

**Comment by jasagredo** [comment]
Why use `input-output-hk/setup-haskell` instead of `input-output-hk/actions/base`?

**Comment by neilmayhew** [comment]
> Why use `input-output-hk/setup-haskell` instead of `input-output-hk/actions/base`?

That's a good question! I wasn't aware of `input-output-hk/actions/haskell` which I assume is what you meant, and which seems to be identical to `input-output-hk/setup-haskell`. Perhaps you should add a deprecation warning to `setup-haskell` telling people to start using `actions/haskell`?

I'll change our `cardano-ledger` workflow to use `actions/haskell`, and I'll also open a PR for this same change on `actions/haskell`.

**Comment by neilmayhew** [comment]
The new PR is input-output-hk/actions#20

**Comment by neilmayhew** [comment]
Closing this in light of the discussion on the new PR

**Pull request closed without merging**
